stages:
  - build_sbb_image

build_sbb_image:
  stage: build_sbb_image  
  variables: 
    DEPLOY_ZIP: '1'
    FIRST_USER_NAME: 'egg'
    FIRST_USER_PASS: 'egg'
    ENABLE_SSH: '1'
    STAGE_LIST: 'stage0 stage1 stage2'
  script: 
    # printing env variables to see if correct values defined above are correct
    - export
    # destroy all cached data from previous runs
    - sudo rm -Rf ./work
    # update apt repos
    - sudo apt-get update  
    # install dependencies
    - sudo apt-get -yy install git vim parted debootstrap zerofree zip dosfstools bsdtar libcap2-bin rsync grep udev xz-utils curl xxd file kmod quilt qemu-user-static
    # build sbb image using variables 
    - export IMG_NAME=faccos-sbb-$(date +%Y.%m.%d.%H.%M.%S) && sudo ./build.sh
    # copy image file to destination
    - cp ./deploy/$IMG_NAME.gz ./mnt/software/IMG/faccos-sbb
  only: 
    - master
