stages:
  - build_sbb_image
  - cleanup

build_sbb_image:
  stage: build_sbb_image  
  script: 
    # update apt repos
    - sudo apt-get update  
    # install dependencies
    - sudo apt-get -yy install git vim parted debootstrap zerofree zip dosfstools bsdtar libcap2-bin rsync grep udev xz-utils curl xxd file kmod quilt qemu-user-static
    # build sbb image using variables 
    - sudo ./build.sh -c smart_black_box.conf
    # rename last file found in below folder using current datetime
    #- $(date +%Y.%m.%d.%H.%M.%S)
    # copy image file to destination
    - cp ./deploy/*.zip /mnt/software/IMG/faccos-sbb
  only: 
    - master

cleanup:
  stage: cleanup
  script:
  - echo "Time to clean up"
  after_script:
  - set "BUILD_DIR=%CI_PROJECT_DIR%"
  - set "BUILD_DIR=%BUILD_DIR:/=\%"
  - echo "Cleaning %BUILD_DIR%"
  - rmdir /S /Q %BUILD_DIR%
  - exit /b 0
