stages:
  - build_images

build_images:
  stage: build_images  
  script: 
    # make sure corect folders exist
    - mkdir -p /opt/pi-gen/
    # cleaning up old working files built by root on previous ci runs
    # comment this line for faster inage building
    - rm -fR /opt/pi-gen/work/*
    # cleaning up old deploying files built by root on previous ci runs
    - rm -fR /opt/pi-gen/deploy/*
    # update apt repos
    - apt-get update  
    # install dependencies
    - apt-get -yy install git vim parted debootstrap zerofree zip dosfstools bsdtar libcap2-bin rsync grep udev xz-utils curl xxd file kmod quilt qemu-user-static
    # generate image for vpn
    - ./build.sh -c base.conf
    # copy vpn image file to destination
    - cp /opt/pi-gen/deploy/*ospi-base.zip /mnt/software/IMG/$CI_COMMIT_REF_NAME/OSPI

  after_script:
    # killing build.sh process if it is executing
    - "kill $(ps aux | grep '[b]uild.sh' | awk '{print $2}') || :"
    # umounting partitions in case last build failed
    - "umount --recursive /opt/pi-gen/work/{stage1,stage0,stage2,stage-base,stage-sbb,stage-hmi}/rootfs/{dev,proc,sys} || :"
  only: 
    - master
    - staging
