stages:
  - build_images

build_images:
  stage: build_images  
  script: 
    # killing build.sh process if it is executing
    - sudo kill $(ps aux | grep '[b]uild.sh' | awk '{print $2}')
    # umounting partitions in case last build failed
    - sudo umount /opt/pi-gen/work/stage0/rootfs/sys
    - sudo umount /opt/pi-gen/work/stage0/rootfs/proc
    - sudo umount /opt/pi-gen/work/stage0/rootfs/dev/pts
    - sudo umount /opt/pi-gen/work/stage0/rootfs/dev
    # make sure corect folders exist
    - sudo mkdir -p /opt/pi-gen/
    # cleaning up old working files built by root on previous ci runs
    # comment this line for faster inage building
    - sudo rm -fR /opt/pi-gen/work/*
    # cleaning up old deploying files built by root on previous ci runs
    - sudo rm -fR /opt/pi-gen/deploy/*
    # update apt repos
    - sudo apt-get update  
    # install dependencies
    - sudo apt-get -yy install git vim parted debootstrap zerofree zip dosfstools bsdtar libcap2-bin rsync grep udev xz-utils curl xxd file kmod quilt qemu-user-static
    # generate image for vpn
    - sudo ./build.sh -c vpn.conf
    # copy vpn image file to destination
    - sudo cp /opt/pi-gen/deploy/*faccos-vpn.zip /mnt/software/IMG/FaccOS\ VPN
    # generate image for sbb
    - sudo ./build.sh -c sbb.conf
    # copy vpn image file to destination
    - sudo cp /opt/pi-gen/deploy/*faccos-sbb.zip /mnt/software/IMG/FaccOS\ SBB
    # generate image for hmi
    - sudo ./build.sh -c hmi.conf
    # copy hmi image file to destination
    - sudo cp /opt/pi-gen/deploy/*faccos-hmi.zip /mnt/software/IMG/FaccOS\ HMI
  only: 
    - master
    