stages:
  - build_images

build_images:
  stage: build_images  
  script: 
    # make sure corect folders exist
    - sudo mkdir -p /opt/pi-gen/
    # cleaning up old working files built by root on previous ci runs
    # comment this line for faster inage building
    - sudo rm -fR /opt/pi-gen/work/*
    # cleaning up old deploying files built by root on previous ci runs
    - sudo rm -fR /opt/pi-gen/deploy/*
    # update apt repos
    - sudo apt-get update  
    # install dependencies
    - sudo apt-get -yy install git vim parted debootstrap zerofree zip dosfstools bsdtar libcap2-bin rsync grep udev xz-utils curl xxd file kmod quilt qemu-user-static
    # build sbb image using variables 
    - sudo ./build.sh -c build.conf
    # copy sbb image file to destination
    - sudo cp /opt/pi-gen/deploy/*faccos-sbb.zip /mnt/software/IMG/FaccOS\ SBB
    # copy hmi image file to destination
    - sudo cp /opt/pi-gen/deploy/*faccos-hmi.zip /mnt/software/IMG/FaccOS\ HMI
  only: 
    - master
    