stages:
  - build_buster
  - build_bullseye

build_bullseye:
  stage: build_bullseye
  tags:
    - shell
  script:
    - CONTINUE=1 sudo ./build-docker.sh -c config
  artifacts:
    paths:
      - /opt/deploy/bullseye/*
    expire_in: 52 week
  only:
    - master
    - staging
