stages:
  - build_bullseye

build_bullseye:
  stage: build_bullseye
  tags:
    - shell
  script:
    - sudo mkdir -p /opt/pi-gen/
    - sudo rm -fR /opt/pi-gen/work/*
    - sudo rm -fR /opt/pi-gen/deploy/*
    - sudo ./build.sh -c base.conf
    - sudo mkdir -p /mnt/registry
    - sudo mount -t nfs 10.1.2.9:/shared/samba/Software /mnt/registry/
    - sudo mkdir -p /mnt/registry/RASPBERRY/ospi
    - sudo cp /opt/pi-gen/deploy/*.zip /mnt/registry/RASPBERRY/ospi
    - sudo umount /mnt/registry
