variables:
  IMAGE_TAG_BASE: $CI_REGISTRY_IMAGE/base

stages:
  - build_smart_black_box_image

build_smart_black_box_image:
  stage: build_smart_black_box_image
  image: debian:stretch
  dependencies: []
  script: 
    - apt update
    - apt-get -yy install git vim parted quilt coreutils qemu-user-static debootstrap zerofree zip dosfstools bsdtar libcap2-bin rsync grep udev xz-utils curl xxd file kmod
    - ./build.sh -c smart_black_box.conf
    - cp ./deploy/*.gz ./mnt/software/IMG/faccos-sbb
  only: 
    - master
