stages:
  - build_buster
  - build_bullseye

build_bullseye:
  stage: build_bullseye
  tags:
    - shell
  script:
    - echo DEPLOY_DIR=$CI_PROJECT_DIR/deploy >> config
    - sudo ./build.sh -c config
    - sudo mkdir -p /mnt/registry
    - sudo mount -t nfs 10.1.2.9:/shared/samba/Software /mnt/registry/
    - sudo mkdir -p /mnt/registry/RASPBERRY/ospi
    - sudo mv $CI_PROJECT_DIR/deploy/*.img /mnt/registry/RASPBERRY/ospi
    - sudo umount /mnt/registry
  only:
    - master
    - staging
