variables:
  IMAGE_TAG_BASE: $CI_REGISTRY_IMAGE/base

stages:
  - build_sbb_image

build_sbb_image:
  stage: build_sbb_image
  image: gitlab.faccousa.net:4567/faccos/facco-os
  dependencies: []
  script: 
    - ./build.sh -c smart_black_box.conf
    - cp ./deploy/*.gz ./mnt/software/IMG/faccos-sbb
  only: 
    - master
