stages:
  - build_buster
  - build_bullseye

build_bullseye:
  stage: build_bullseye
  tags:
    - shell
  script:
    - sudo ./build.sh -c config
  artifacts:
    paths:
      - /opt/deploy/*
    expire_in: 52 week
  only:
    - master
    - staging
