stages:
  - build_images

build_images:
  stage: build_images
  script:
    # update apt repos
    - apt-get update  
    # install dependencies
    - apt-get -yy install git coreutils quilt parted debootstrap zerofree zip libarchive-tools
    - apt-get -yy install libcap2-bin grep rsync xz-utils file git curl bc kpartx wget
    - apt-get -yy install qemu-user-static dosfstools xxd kmod qemu-utils
#    - wget -O- get.docker.com | sh
    - ./build.sh -c config
    # Clean env
#    - docker rm -v pigen_work
    # generate image for vpn
#    - ./build-docker.sh -c config
  artifacts:
    paths:
      - /opt/deploy/*
    expire_in: 52 week
  only:
    - master
    - staging
