stages:
  - build_buster
  - build_bullseye

build_bullseye:
  stage: build_bullseye
  tags:
    - shell
  script:
    - echo 'DEPLOY_DIR=${CI_PROJECT_DIR}/deploy' >> config
    - cat config
    - sudo ./build.sh -c config
  artifacts:
    paths:
      - $CI_PROJECT_DIR/deploy/*
    expire_in: 52 week
  only:
    - master
    - staging
