name: Build Fedora Raspberry Pi Image

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libguestfs-tools

      - name: Build Fedora Image
        run: |
          curl -O https://download.fedoraproject.org/pub/fedora/linux/releases/33/Everything/aarch64/os/images/Fedora-Everything-netinst-aarch64-33-1.2.iso
          mkdir -p iso_mount ks_output
          sudo mount -o loop Fedora-Everything-netinst-aarch64-33-1.2.iso iso_mount
          sudo virt-builder --size 4G --format raw --arch aarch64 --install cloud-init --init minimal --run-command 'mkdir /boot/efi' --output fedora-rpi.img
          sudo livemedia-creator --ks=fedora-rpi.ks --no-virt --make-disk --image-name=fedora-rpi.img --arm-platform=rpi4 --disk-image --image-only

      - name: Upload Fedora Image
        uses: actions/upload-artifact@v2
        with:
          name: fedora-rpi
          path: fedora-rpi.img
